---
book_repo: pivotal-cf/docs-book-ipsec
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.9'
  directory: addon-ipsec/1-9
  subnav_template: addon_ipsec_1-9.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: IPsec Add-On for PCF
    search_placeholder: Search IPsec Add-On 1.9
    url_prefix: addon-ipsec/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.5.pdf">v1.5</a>

- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.8'
  directory: addon-ipsec/1-8
  subnav_template: addon_ipsec_1-8.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: IPsec Add-On for PCF
    search_placeholder: Search IPsec Add-On 1.8
    url_prefix: addon-ipsec/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.5.pdf">v1.5</a>

- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.7'
  directory: addon-ipsec/1-7
  subnav_template: addon_ipsec_1-7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: IPsec Add-On for PCF
    search_placeholder: Search IPsec Add-On 1.7
    url_prefix: addon-ipsec/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.5.pdf">v1.5</a>
